In [1]:
import sys, os
import numpy as np

In [2]:
thisdir = os.path.dirname('__file__')
libpath = os.path.join(thisdir, '../c3dp')
if not libpath in sys.path:
    sys.path.insert(0, libpath)

In [3]:
import gauge_volume as gv

In [19]:
sample_height=26. #mm
sample_width=4.16 #mm
collimator_openningSize_sample=3. # channel opening size
collimator_inner_radius=16.02
coll_length=380. #mm
collimator_outer_radius=coll_length+collimator_inner_radius
collimator_openningSize_detector=(collimator_outer_radius*collimator_openningSize_sample)/collimator_inner_radius

pointsNum_z=10
pointsNum_y=5
stepsize=0.1
zS=np.linspace(-sample_height/2., sample_height/2., num=pointsNum_z) #sample_positions_z vertical
yS=np.linspace(-sample_width/2., sample_width/2., num=pointsNum_y) #sample_positions_y
# zS=np.arange(-sample_height/2., sample_height/2., stepsize) #sample_positions_z vertical
# yS=np.arange(-sample_width/2., sample_width/2., stepsize) #sample_positions_y
# xS=np.linspace(-sample_width/2., sample_width/2., num=pointsNum_y) #sample_positions_x
xS=0.

In [33]:
list_points=[]
for valY in yS:
    for valZ in zS:
        list_points.append([xS, valY, valZ])
arr=np.array(list_points)
arr.shape

(50, 3)

(50, 3)

In [34]:
m=np.array(np.meshgrid(xS,yS,zS))

In [35]:
m.shape

(3, 5, 1, 10)

In [36]:
m=m.transpose(1,2,3,0)
m.shape

(5, 1, 10, 3)

In [38]:
m.shape=-1,3
m.shape

(50, 3)

In [28]:
m

array([[  0.        ,  -2.08      , -13.        ],
       [  0.        ,  -2.08      , -10.11111111],
       [  0.        ,  -2.08      ,  -7.22222222],
       [  0.        ,  -2.08      ,  -4.33333333],
       [  0.        ,  -2.08      ,  -1.44444444],
       [  0.        ,  -2.08      ,   1.44444444],
       [  0.        ,  -2.08      ,   4.33333333],
       [  0.        ,  -2.08      ,   7.22222222],
       [  0.        ,  -2.08      ,  10.11111111],
       [  0.        ,  -2.08      ,  13.        ],
       [  0.        ,  -1.04      , -13.        ],
       [  0.        ,  -1.04      , -10.11111111],
       [  0.        ,  -1.04      ,  -7.22222222],
       [  0.        ,  -1.04      ,  -4.33333333],
       [  0.        ,  -1.04      ,  -1.44444444],
       [  0.        ,  -1.04      ,   1.44444444],
       [  0.        ,  -1.04      ,   4.33333333],
       [  0.        ,  -1.04      ,   7.22222222],
       [  0.        ,  -1.04      ,  10.11111111],
       [  0.        ,  -1.04   

In [29]:
arr

array([[  0.        ,  -2.08      , -13.        ],
       [  0.        ,  -2.08      , -10.11111111],
       [  0.        ,  -2.08      ,  -7.22222222],
       [  0.        ,  -2.08      ,  -4.33333333],
       [  0.        ,  -2.08      ,  -1.44444444],
       [  0.        ,  -2.08      ,   1.44444444],
       [  0.        ,  -2.08      ,   4.33333333],
       [  0.        ,  -2.08      ,   7.22222222],
       [  0.        ,  -2.08      ,  10.11111111],
       [  0.        ,  -2.08      ,  13.        ],
       [  0.        ,  -1.04      , -13.        ],
       [  0.        ,  -1.04      , -10.11111111],
       [  0.        ,  -1.04      ,  -7.22222222],
       [  0.        ,  -1.04      ,  -4.33333333],
       [  0.        ,  -1.04      ,  -1.44444444],
       [  0.        ,  -1.04      ,   1.44444444],
       [  0.        ,  -1.04      ,   4.33333333],
       [  0.        ,  -1.04      ,   7.22222222],
       [  0.        ,  -1.04      ,  10.11111111],
       [  0.        ,  -1.04   

In [136]:
norm_x_y=np.sqrt(m[:, 0]**2+m[:,1]**2)
norm_x_y

array([[ 2.94156421,  2.80014285,  2.6587215 ,  2.51730014,  2.37587878,
         2.23445743,  2.09303607,  1.95161472,  1.81019336,  1.668772  ,
         1.52735065,  1.38592929,  1.24450793,  1.10308658,  0.96166522,
         0.82024387,  0.67882251,  0.53740115,  0.3959798 ,  0.25455844,
         0.11313708,  0.02828427,  0.16970563,  0.31112698,  0.45254834,
         0.5939697 ,  0.73539105,  0.87681241,  1.01823376,  1.15965512,
         1.30107648,  1.44249783,  1.58391919,  1.72534055,  1.8667619 ,
         2.00818326,  2.14960461,  2.29102597,  2.43244733,  2.57386868,
         2.71529004,  2.8567114 ],
       [18.31420214, 18.31420214, 18.31420214, 18.31420214, 18.31420214,
        18.31420214, 18.31420214, 18.31420214, 18.31420214, 18.31420214,
        18.31420214, 18.31420214, 18.31420214, 18.31420214, 18.31420214,
        18.31420214, 18.31420214, 18.31420214, 18.31420214, 18.31420214,
        18.31420214, 18.31420214, 18.31420214, 18.31420214, 18.31420214,
        18.31420

In [137]:
m[:,[1,2]]

array([[[ -2.08,  -1.98,  -1.88,  -1.78,  -1.68,  -1.58,  -1.48,  -1.38,
          -1.28,  -1.18,  -1.08,  -0.98,  -0.88,  -0.78,  -0.68,  -0.58,
          -0.48,  -0.38,  -0.28,  -0.18,  -0.08,   0.02,   0.12,   0.22,
           0.32,   0.42,   0.52,   0.62,   0.72,   0.82,   0.92,   1.02,
           1.12,   1.22,   1.32,   1.42,   1.52,   1.62,   1.72,   1.82,
           1.92,   2.02],
        [ -2.08,  -1.98,  -1.88,  -1.78,  -1.68,  -1.58,  -1.48,  -1.38,
          -1.28,  -1.18,  -1.08,  -0.98,  -0.88,  -0.78,  -0.68,  -0.58,
          -0.48,  -0.38,  -0.28,  -0.18,  -0.08,   0.02,   0.12,   0.22,
           0.32,   0.42,   0.52,   0.62,   0.72,   0.82,   0.92,   1.02,
           1.12,   1.22,   1.32,   1.42,   1.52,   1.62,   1.72,   1.82,
           1.92,   2.02]],

       [[-12.9 , -12.9 , -12.9 , -12.9 , -12.9 , -12.9 , -12.9 , -12.9 ,
         -12.9 , -12.9 , -12.9 , -12.9 , -12.9 , -12.9 , -12.9 , -12.9 ,
         -12.9 , -12.9 , -12.9 , -12.9 , -12.9 , -12.9 , -12.9 , -12.9

In [138]:
Cs_square = gv.make_square(collimator_inner_radius, collimator_openningSize_sample)
Cd_square = gv.make_square(collimator_outer_radius, collimator_openningSize_detector)
sample_points = arr

theta_phiS = gv.theta_phi(Cs_square, sample_points)
theta_phiD = gv.theta_phi(Cd_square, sample_points)

In [139]:
sample_points

array([[  0.  ,  -2.08, -13.  ],
       [  0.  ,  -2.08, -12.9 ],
       [  0.  ,  -2.08, -12.8 ],
       ...,
       [  0.  ,   2.02,  12.7 ],
       [  0.  ,   2.02,  12.8 ],
       [  0.  ,   2.02,  12.9 ]])

In [140]:
sample_points[0]

array([  0.  ,  -2.08, -13.  ])

In [141]:
sample_points[1]

array([  0.  ,  -2.08, -12.9 ])

In [142]:
sample_points[20]

array([  0.  ,  -2.08, -11.  ])

In [143]:
sample_points[400]

array([ 0.  , -1.98,  1.  ])

In [144]:
the_phi=np.array(np.rad2deg(theta_phiS))
the_phi

array([[[ -92.07347339, -102.59695384, -102.59695384,  -92.07347339],
        [ -92.07347339, -102.59695384, -102.59695384,  -92.07347339],
        [ -92.07347339, -102.59695384, -102.59695384,  -92.07347339],
        ...,
        [ -77.60759251,  -88.14086465,  -88.14086465,  -77.60759251],
        [ -77.60759251,  -88.14086465,  -88.14086465,  -77.60759251],
        [ -77.60759251,  -88.14086465,  -88.14086465,  -77.60759251]],

       [[ 132.13016087,  131.45515559,  125.01404014,  125.65500153],
        [ 131.93296854,  131.25850088,  124.77923874,  125.41832814],
        [ 131.73454935,  131.06065478,  124.54309321,  125.18025606],
        ...,
        [  55.67329433,   55.05576395,   48.46145091,   49.11596012],
        [  55.43573343,   54.81627858,   48.26179517,   48.91689446],
        [  55.19952198,   54.57819635,   48.06337317,   48.7190275 ]]])

In [145]:
the_phi.shape

(2, 10920, 4)

In [146]:
the_phiT=the_phi.transpose(1,0,2).transpose(0,2,1)
the_phiT

array([[[ -92.07347339,  132.13016087],
        [-102.59695384,  131.45515559],
        [-102.59695384,  125.01404014],
        [ -92.07347339,  125.65500153]],

       [[ -92.07347339,  131.93296854],
        [-102.59695384,  131.25850088],
        [-102.59695384,  124.77923874],
        [ -92.07347339,  125.41832814]],

       [[ -92.07347339,  131.73454935],
        [-102.59695384,  131.06065478],
        [-102.59695384,  124.54309321],
        [ -92.07347339,  125.18025606]],

       ...,

       [[ -77.60759251,   55.67329433],
        [ -88.14086465,   55.05576395],
        [ -88.14086465,   48.46145091],
        [ -77.60759251,   49.11596012]],

       [[ -77.60759251,   55.43573343],
        [ -88.14086465,   54.81627858],
        [ -88.14086465,   48.26179517],
        [ -77.60759251,   48.91689446]],

       [[ -77.60759251,   55.19952198],
        [ -88.14086465,   54.57819635],
        [ -88.14086465,   48.06337317],
        [ -77.60759251,   48.7190275 ]]])

In [147]:
Syz=arr[:,[1,2]].T

In [148]:
sample_pos, gauge_volume = gv.gauge_volume(theta_phiS, theta_phiD, Syz)

In [149]:
print (len(gauge_volume))
print (sample_points.shape)
print (sample_pos.shape)

10920
(10920, 3)
(2, 10920)


In [ ]:
gv.making_plot(sample_pos, gauge_volume )